sudo: required

matrix:
  include:
    - os: linux
      jdk: openjdk8
      language: scala
    - os: linux
      jdk: openjdk11
      language: scala
    - os: linux
      jdk: openjdk11
      arch: s390x
      language: java

services:
  - docker

scala:
  - 2.12.8

script:
  - ./script/travis-deploy.sh
